title: Martinetoye
default_lang: en
author:
  name: 'Martin Toye'
  email: 'martin.toye@me.com'
  gravatar: 'https://s.gravatar.com/avatar/d0ac991626368c511b1a101dc9010443?s=80'
taxonomies:
  - tag
metadata:
  description: 'A ruthless, insulting guide to being an adult and doing grown up things'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
description: 'The  guide to growing up, you moron'
owner:
  name: 'Martin Toye'
  email: martin.toye@me.com
  description: 'Professional Front End Developer'
  phone: '07864873669'
  address: 'Banstead, Surrey'
  image: /user/themes/meaty/images/me.png
  resume: 'https://drive.google.com/open?id=1RV62LQmfKAkxag0HKvDd6pTNyGx5LKM5'
social:
  -
    title: Facebook
    url: 'https://facebook.com/mtoye1'
    class: facebook
  -
    title: twitter
    url: 'https://twitter.com/martinetoye'
    class: twitter
  -
    title: Instagram
    url: 'https://instagram.com/martinetoye'
    class: instagram
  -
    title: github
    url: 'https://github.com/martinetoye'
    class: github
logo: /user/themes/meaty/images/logo.png
links:
  -
    title: Home
    url: ../
  -
    title: About
    url: '../#about'
  -
    title: Portfolio
    url: '../#portfolio'
  -
    title: 'Say Hi'
    url: '../#contact'
  -
    title: 'Hire Me'
    class: 'btn btn__blue modal__toggle'
include:
  - .htaccess
exclude:
  - lib
  - config.rb
  - Gemfile
  - Capfile
  - Gemfile.lock
  - config
  - log
  - Rakefile
  - Rakefile.rb
  - tmp
  - less
  - '*.sublime-project'
  - '*.sublime-workspace'
  - test
  - spec
  - Gruntfile.js
  - package.json
  - node_modules
